import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { CliUsageError } from "../errors.js";
import { withRuntime } from "../runtime-command.js";

/**
 * Options for generating the PostgreSQL forced-RLS policy DDL that the shared
 * engine validates at startup (`validatePostgresRlsPolicies`). See ADR-0036.
 */
export interface PolicyGenerationOptions {
  /** Tenant tables to secure. Plain or `schema.table`; unquoted identifiers. */
  readonly tables: readonly string[];
  /** The non-owner, non-superuser, non-BYPASSRLS runtime role to grant. */
  readonly role: string;
  /** The tenant discriminator column. Defaults to `tenant_id`. */
  readonly tenantColumn?: string;
}

const DEFAULT_TENANT_COLUMN = "tenant_id";

// Postgres unquoted identifier. We generate DDL rather than execute it, but we
// still refuse anything that isn't a plain identifier so the output can never
// carry an injection or a broken statement. Schema-qualified names are split
// and each segment validated.
const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_$]*$/;

function assertIdentifier(value: string, label: string): void {
  const trimmed = value.trim();
  if (trimmed === "") {
    throw new CliUsageError(`${label} cannot be empty.`);
  }
  const segments = trimmed.split(".");
  for (const segment of segments) {
    if (!IDENTIFIER.test(segment)) {
      throw new CliUsageError(
        `${label} "${value}" is not a plain SQL identifier. ` +
          "Use letters, digits, and underscores (optionally schema.table).",
      );
    }
  }
}

/** The unqualified last segment of a possibly schema-qualified table name. */
function tableLeaf(table: string): string {
  const segments = table.trim().split(".");
  return segments[segments.length - 1]!;
}

/**
 * Emit review-ready forced-RLS DDL for the given tenant tables. Pure and
 * deterministic: it opens no connection and executes nothing. The predicate is
 * "central sees all, a tenant sees only its own rows", and both `USING` and
 * `WITH CHECK` read `tenancyjs.tenant_id` and `tenancyjs.is_central` so the
 * output satisfies the startup validator.
 */
export function generatePolicySql(options: PolicyGenerationOptions): string {
  if (options.tables.length === 0) {
    throw new CliUsageError("policy requires at least one --table.");
  }
  assertIdentifier(options.role, "--role");
  const column = options.tenantColumn ?? DEFAULT_TENANT_COLUMN;
  assertIdentifier(column, "--tenant-column");
  for (const table of options.tables) {
    assertIdentifier(table, "--table");
  }

  const header = [
    "-- Generated by `tenancy policy` (TenancyJS). Review before applying.",
    "-- TenancyJS never executes this; apply it with your own migration tool.",
    `-- Tenant column: ${column} (must match your adapter's tenantColumn).`,
    `-- Runtime role: ${options.role} (must be NOSUPERUSER, NOBYPASSRLS, and must NOT own these tables).`,
    "--",
    "-- Create the runtime role first if it does not exist, e.g.:",
    `--   CREATE ROLE ${options.role} LOGIN PASSWORD '...' NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;`,
    "",
  ].join("\n");

  const predicate = [
    "    current_setting('tenancyjs.is_central', true) = 'true'",
    `    OR ${column} = current_setting('tenancyjs.tenant_id', true)`,
  ].join("\n");

  const blocks = options.tables.map((table) => {
    const qualified = table.trim();
    const policy = `${tableLeaf(qualified)}_tenant_isolation`;
    return [
      `-- ${qualified}`,
      `ALTER TABLE ${qualified} ENABLE ROW LEVEL SECURITY;`,
      `ALTER TABLE ${qualified} FORCE ROW LEVEL SECURITY;`,
      `DROP POLICY IF EXISTS ${policy} ON ${qualified};`,
      `CREATE POLICY ${policy} ON ${qualified}`,
      `  USING (`,
      predicate,
      `  )`,
      `  WITH CHECK (`,
      predicate,
      `  );`,
      `REVOKE ALL ON ${qualified} FROM PUBLIC;`,
      `GRANT SELECT, INSERT, UPDATE, DELETE ON ${qualified} TO ${options.role};`,
    ].join("\n");
  });

  return `${header}${blocks.join("\n\n")}\n`;
}

export interface RunPolicyOptions extends PolicyGenerationOptions {
  readonly out?: string;
  readonly json: boolean;
  readonly root: string;
}

export interface RunPolicyResult {
  readonly schemaVersion: 1;
  readonly command: "policy";
  readonly tables: readonly string[];
  readonly role: string;
  readonly tenantColumn: string;
  readonly sql: string;
  readonly writtenTo?: string;
}

/**
 * Build the policy result and, when `--out` is given, write the SQL to a file
 * (relative to the project root). Writing a file is the only side effect.
 */
export function runPolicy(options: RunPolicyOptions): RunPolicyResult {
  const sql = generatePolicySql(options);
  const tenantColumn = options.tenantColumn ?? DEFAULT_TENANT_COLUMN;
  let writtenTo: string | undefined;
  if (options.out !== undefined) {
    const target = resolve(options.root, options.out);
    writeFileSync(target, sql, "utf8");
    writtenTo = target;
  }
  return {
    schemaVersion: 1,
    command: "policy",
    tables: options.tables,
    role: options.role,
    tenantColumn,
    sql,
    ...(writtenTo === undefined ? {} : { writtenTo }),
  };
}

export interface ApplyPolicyOptions extends PolicyGenerationOptions {
  readonly root: string;
  readonly configPath?: string;
}

export interface ApplyPolicyResult {
  readonly schemaVersion: 1;
  readonly command: "policy";
  readonly applied: true;
  readonly tables: readonly string[];
  readonly role: string;
  readonly tenantColumn: string;
}

/**
 * Apply the generated forced-RLS DDL through the host runtime's privileged
 * `admin` connection (opt-in `--apply`). It reuses `generatePolicySql` — the
 * exact SQL `tenancy policy` prints — so generate and apply never drift. The
 * statements are idempotent (`ENABLE`/`FORCE` RLS, `DROP POLICY IF EXISTS` +
 * `CREATE POLICY`, `GRANT`); it does NOT create the runtime role. Fails closed
 * when the runtime exposes no `admin` connection.
 */
export async function runPolicyApply(
  options: ApplyPolicyOptions,
): Promise<ApplyPolicyResult> {
  // Generate (and validate identifiers) before touching the database.
  const sql = generatePolicySql(options);
  const tenantColumn = options.tenantColumn ?? DEFAULT_TENANT_COLUMN;
  return withRuntime(
    {
      root: options.root,
      ...(options.configPath === undefined
        ? {}
        : { configPath: options.configPath }),
    },
    async (runtime) => {
      if (runtime.admin === undefined) {
        throw new CliUsageError(
          "policy --apply needs a privileged admin connection. Add `admin` (e.g. a pg Pool " +
            "on ADMIN_DATABASE_URL) to defineTenancyRuntime — kept separate from your fail-closed " +
            "runtime role, which must never run DDL.",
        );
      }
      await runtime.admin.query(sql);
      return {
        schemaVersion: 1 as const,
        command: "policy" as const,
        applied: true as const,
        tables: options.tables,
        role: options.role,
        tenantColumn,
      };
    },
  );
}
